version: "3.9"

services:
  frontend:
    build: .
    container_name: qimchi_frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
