$ErrorActionPreference = "Stop"

# NOTE: $ErrorActionPreference only governs CMDLETS. A failing native command
# (uv, npm, pyinstaller, ISCC) sets $LASTEXITCODE and execution continues, so
# every native call below is followed by Assert-LastExit. Without this a failed
# dependency install silently cascades into a "successful" build of stale output.
function Assert-LastExit {
    param([Parameter(Mandatory = $true)][string]$What)
    if ($LASTEXITCODE -ne 0) {
        throw "$What failed (exit code $LASTEXITCODE)"
    }
}

# Artifacts must be removed BEFORE the step that produces them. Otherwise a
# failed step leaves last run's file in place and the usual "Test-Path" check
# reports success for output that can be old.
function Remove-StaleArtifact {
    param([Parameter(Mandatory = $true)][string]$Path)
    if (Test-Path $Path) {
        Remove-Item -Recurse -Force $Path -ErrorAction SilentlyContinue
    }
    if (Test-Path $Path) {
        throw "Could not clear previous artifact at $Path (is it running or open?)"
    }
}

# A running Qimchi locks files inside packaging/build/qimchi (it writes a
# .__qimchi.lock into its own bundle dir), which makes both the PyInstaller
# clean and the Inno Setup compile fail with an unhelpful sharing violation.
# Fail fast with an actionable message instead.
$runningQimchi = Get-Process -Name "qimchi" -ErrorAction SilentlyContinue
if ($runningQimchi) {
    $ids = ($runningQimchi | ForEach-Object { $_.Id }) -join ", "
    throw "Qimchi is running (PID $ids) and will lock build output. Close it (or: Stop-Process -Id $ids -Force) and re-run."
}

# Extract version from pyproject.toml for use in the installer filename/metadata.
$VERSION = (Select-String -Path "backend/pyproject.toml" -Pattern 'version\s*=\s*"([^"]+)"').Matches.Groups[1].Value
$frontendVersion = $env:QIMCHI_VERSION
if ([string]::IsNullOrWhiteSpace($frontendVersion)) {
    $frontendVersion = $env:CI_COMMIT_TAG
}
if ([string]::IsNullOrWhiteSpace($frontendVersion)) {
    $frontendVersion = git tag --points-at HEAD --list "v*" | Select-Object -First 1
}
if ([string]::IsNullOrWhiteSpace($frontendVersion)) {
    $frontendVersion = $VERSION
}
Write-Host "Building Qimchi v$VERSION (footer version: $frontendVersion)..."

# ── 1. Frontend ───────────────────────────────────────────────────────────────
Write-Host "Building React frontend..."
Set-Location frontend
npm install
Assert-LastExit "npm install"
$originalQimchiVersion = $env:QIMCHI_VERSION
$env:QIMCHI_VERSION = $frontendVersion
npm run build
$frontendBuildExit = $LASTEXITCODE
if ($null -eq $originalQimchiVersion) {
    Remove-Item Env:QIMCHI_VERSION
} else {
    $env:QIMCHI_VERSION = $originalQimchiVersion
}
if ($frontendBuildExit -ne 0) {
    throw "npm run build (tsc/vite) failed (exit code $frontendBuildExit)"
}
Set-Location ..
if (!(Test-Path "frontend/dist/index.html")) {
    throw "Frontend build produced no dist/index.html"
}

# ── 2. Staging area ───────────────────────────────────────────────────────────
Write-Host "Creating packaging/build directory..."
New-Item -ItemType Directory -Force -Path packaging/build | Out-Null
Copy-Item frontend/public/qimchi-logo.ico packaging/build/

Write-Host "Copying canonical python launcher..."
# The launcher is committed at packaging/qimchi_launcher.py (source of truth).
Copy-Item packaging/qimchi_launcher.py packaging/build/qimchi_launcher.py -Force

Write-Host "Staging backend source (excluding venv/caches/logs)..."
# IMPORTANT: do NOT --add-data the whole backend/ folder.
# Stage only the runtime source: main.py + the api package (+ .env if present).
$backendStage = Join-Path (Get-Location) "packaging\build\backend_src"
Remove-Item -Recurse -Force $backendStage -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force -Path $backendStage | Out-Null
Copy-Item backend/main.py $backendStage/
Copy-Item -Recurse backend/api $backendStage/api
if (Test-Path backend/.env) { Copy-Item backend/.env $backendStage/ }
Get-ChildItem -Path $backendStage -Recurse -Force -Directory -Filter "__pycache__" |
    Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

# Stamp the tag this build was cut from. pyproject.toml carries the BASE
# version only, so without this a -rc install cannot tell it is a preview and
# the updater never offers it the stable release of the same version.
Write-Host "Stamping build version: $frontendVersion"
$stampPath = Join-Path $backendStage "api\_build_version.py"
$stampLines = @(
    "# Generated by build_local.ps1 -- do not edit.",
    ('BUILD_VERSION = "' + $frontendVersion + '"')
)
Set-Content -Path $stampPath -Value $stampLines -Encoding ASCII

# ── 3. fd binary ──────────────────────────────────────────────────────────────
# fd is bundled into the PyInstaller package so users don't need it on PATH.
# The binary is NOT committed (vendor/.gitignore excludes it); download it once.
Write-Host "Ensuring vendor/fd-windows/fd.exe is present..."
New-Item -ItemType Directory -Force -Path "vendor\fd-windows" | Out-Null
$fdDest = "vendor\fd-windows\fd.exe"
# Presence alone isn't enough: a truncated/failed download leaves a small or
# empty fd.exe that passes Test-Path and then breaks the Explorer at runtime.
$fdOk = (Test-Path $fdDest) -and ((Get-Item $fdDest).Length -gt 200KB)
if ((Test-Path $fdDest) -and (!$fdOk)) {
    Write-Warning "  fd.exe present but looks truncated -- re-downloading."
    Remove-Item -Force $fdDest -ErrorAction SilentlyContinue
}
if (!$fdOk) {
    Write-Host "  fd.exe not found -- downloading from GitHub releases..."
    try {
        $rel   = Invoke-RestMethod "https://api.github.com/repos/sharkdp/fd/releases/latest"
        $asset = $rel.assets | Where-Object {
            $_.name -like "*x86_64-pc-windows-msvc*" -and $_.name -like "*.zip"
        } | Select-Object -First 1
        if (!$asset) { throw "Could not locate fd Windows asset in latest release." }

        $zipTemp     = Join-Path $env:TEMP "fd-windows.zip"
        $extractTemp = Join-Path $env:TEMP "fd-extract"
        Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $zipTemp
        Expand-Archive $zipTemp -DestinationPath $extractTemp -Force
        $fdExe = Get-ChildItem -Path $extractTemp -Recurse -Filter "fd.exe" | Select-Object -First 1
        Copy-Item $fdExe.FullName $fdDest -Force
        Remove-Item $zipTemp       -Force -ErrorAction SilentlyContinue
        Remove-Item $extractTemp   -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "  Downloaded fd.exe ($([math]::Round((Get-Item $fdDest).Length / 1KB, 0)) KB) to $fdDest"
    } catch {
        Write-Warning "  Failed to download fd.exe: $_"
        Write-Warning "  Explorer's directory tree will not work in the packaged app."
        Write-Warning "  Place fd.exe manually at $fdDest and re-run to fix."
    }
} else {
    Write-Host "  fd.exe already present at $fdDest"
}

# ── 4. Python environment ─────────────────────────────────────────────────────
Write-Host "Setting up Python environment (backend/.venv -- the complete env)..."
# Build from backend/.venv: it has the full runtime deps incl. the datasets
# extra (netCDF4, polars, h5py, h5netcdf, numcodecs). The root .venv is missing
# netCDF4/polars, so we deliberately do NOT use it.
$buildVenv = Join-Path (Get-Location) "backend\.venv"
$pythonExe = Join-Path $buildVenv "Scripts\python.exe"

# Test-Path is not enough: uv-managed base interpreters get garbage-collected on
# upgrade, which leaves python.exe on disk pointing at a home that no longer
# exists. It looks fine and fails on first use. Actually run it.
$venvOk = $false
if (Test-Path $pythonExe) {
    & $pythonExe -c "import sys" 2>&1 | Out-Null
    $venvOk = ($LASTEXITCODE -eq 0)
    if (!$venvOk) {
        Write-Warning "  backend/.venv exists but its interpreter does not run"
        Write-Warning "  (its uv-managed base Python was probably removed) -- recreating."
        Remove-Item -Recurse -Force $buildVenv -ErrorAction SilentlyContinue
    }
}
if (!$venvOk) {
    uv venv --python 3.13 $buildVenv
    Assert-LastExit "uv venv"
    & $pythonExe -c "import sys" 2>&1 | Out-Null
    Assert-LastExit "newly created venv interpreter"
}

Write-Host "Installing dependencies (backend + datasets/test extras + build tools)..."
# Editable backend WITH the datasets extra so NetCDF/HDF5/polars loaders work.
uv pip install --python $pythonExe -e ".\backend[datasets,test]"
Assert-LastExit "uv pip install backend[datasets,test]"
# pythonnet is required by pywebview's EdgeChromium (WebView2) backend on Windows.
uv pip install --python $pythonExe pyinstaller pywebview pythonnet uvicorn
Assert-LastExit "uv pip install build tools"

# The spec calls copy_metadata("qimchi-api"); if the editable install silently
# produced no metadata, PyInstaller fails minutes later with an opaque error.
& $pythonExe -c "import importlib.metadata as m; m.distribution('qimchi-api')" 2>&1 | Out-Null
Assert-LastExit "qimchi-api metadata check (editable install incomplete?)"

# ── 5. PyInstaller (onedir) ───────────────────────────────────────────────────
Write-Host "Building onedir app with PyInstaller..."
# Uses the canonical spec at packaging/qimchi.spec (committed; portable paths).
# Output: packaging/build/qimchi/           <-- COLLECT output dir
#           qimchi.exe
#           _internal/  (Python runtime, deps, fd.exe, frontend/backend data)
$appDir = "packaging/build/qimchi"
$appExe = "$appDir/qimchi.exe"
# Clear the previous app BEFORE building, so the check afterwards proves this
# run produced it. Otherwise a failed PyInstaller run leaves the old onedir in
# place and the build reports success for an old binary.
Remove-StaleArtifact $appDir

$pyiArgs = @(
    "--clean", "--noconfirm",
    "--distpath", "packaging/build",
    "--workpath", "packaging/build/pyinstaller_work",
    "packaging/qimchi.spec"
)
& $pythonExe -m PyInstaller @pyiArgs
Assert-LastExit "PyInstaller"

if (!(Test-Path $appExe)) {
    throw "PyInstaller reported success but $appExe was not produced"
}
$dirSize = (Get-ChildItem -Recurse $appDir | Measure-Object -Property Length -Sum).Sum / 1MB
Write-Host "Built $appDir ($([math]::Round($dirSize, 0)) MB total)"

# ── 6. Inno Setup installer ───────────────────────────────────────────────────
Write-Host "Building Inno Setup installer..."
# Locate ISCC.exe (installed by choco install innosetup or manually).
$isccExe = $null
# Windows PowerShell 5.1 (the CI runner's shell) has no ?. operator, so resolve
# the ISCC.exe command separately before building the candidate list.
$isccCmd = Get-Command "ISCC.exe" -ErrorAction SilentlyContinue
$isccCandidates = @(
    $(if ($isccCmd) { $isccCmd.Source }),
    "$env:ProgramFiles\Inno Setup 6\ISCC.exe",
    "${env:ProgramFiles(x86)}\Inno Setup 6\ISCC.exe",
    # Inno Setup's non-admin ("just me") install lands here and is NOT on PATH.
    "$env:LOCALAPPDATA\Programs\Inno Setup 6\ISCC.exe"
)
foreach ($cand in $isccCandidates) {
    if ($cand -and (Test-Path $cand)) { $isccExe = $cand; break }
}

$installerPath = "packaging\build\qimchi-setup.exe"
# Clear the previous installer BEFORE this step, including on the skip path.
Remove-StaleArtifact $installerPath

if (!$isccExe) {
    Write-Warning "ISCC.exe not found -- SKIPPING installer build."
    Write-Warning "Install Inno Setup 6 (https://jrsoftware.org/isinfo.php or: choco install innosetup) then re-run."
    Write-Warning "NOTE: no qimchi-setup.exe was produced by this run."
    Write-Host "Packaged app is at: $(Get-Location)\$appDir"
} else {
    # /Q = quiet (no progress window); /DAppVersion passes the version to the script.
    & $isccExe "/DAppVersion=$VERSION" "/Q" "packaging\setup.iss"
    Assert-LastExit "Inno Setup (ISCC)"
    if (!(Test-Path $installerPath)) {
        throw "ISCC reported success but $installerPath was not produced"
    }
    $installerSize = (Get-Item $installerPath).Length / 1MB
    Write-Host "Installer: $(Get-Location)\$installerPath ($([math]::Round($installerSize, 0)) MB)"
}
