services:
  qimchi-react:
    build: .
    image: qimchi-react:latest
    container_name: qimchi-react
    ports:
      - "8000:8000" # backend
      - "80:80" # frontend/nginx
    environment:
      - LOG_LEVEL=INFO
      - GUNICORN_WORKERS=8
    volumes:
      - ./data:/data:rw
    restart: unless-stopped
