[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:fastapi]
command=uv run uvicorn main:app --host 127.0.0.1 --port 8000 --workers 8 --log-level info --ws-max-size 20000000 --ws-ping-interval 20 --ws-ping-timeout 20
directory=/app
environment=SERVE_STATIC_FILES="true"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/fastapi.err.log
stdout_logfile=/var/log/supervisor/fastapi.out.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log
