[project]
name = "qimchi-api"
version = "0.4.0"
description = "Plot your spicy quantum measurements with ease"
authors = [
  { name = "Spandan Anupam", email = "s.anupam@fz-juelich.de" },
  { name = "Jyotirmaya Shivottam", email = "jyotirmaya.shivottam@niser.ac.in" },
  { name = "Lino Visser", email = "l.visser@fz-juelich.de" },
]
license = "AGPL-3.0-or-later"
keywords = ["quantum", "plotter", "plotly", "fastapi", "react"]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.115.12",
    "gunicorn>=23.0.0",
    "kaleido>=1.0.0",
    "numpy>=2.2.4",
    "pip>=25.2",
    "plotly>=6.0.1",
    "pydantic>=2.11.3",
    "pytest>=9.0.1",
    "pytest-asyncio>=1.0.0",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "ruff>=0.12.10",
    "scikit-image>=0.25.2",
    "setuptools>=80.9.0",
    "watchdog>=6.0.0",
    "websockets>=15.0.1",
    "wheel>=0.45.1",
    "xarray>=2025.3.1",
    "zarr==2.18.4",
    "concurrent-log-handler==0.9.29",
    "portalocker==3.2.0",
]

[project.urls]
homepage = "https://gitlab.com/squad-lab/qimchi"
documentation = "https://qimchi.squad-lab.org"
repository = "https://gitlab.com/squad-lab/qimchi"
