#!/usr/bin/env bash
# Build script for Qimchi macOS .app bundle and .dmg.
#
# Prerequisites (install once):
#   # uv — https://docs.astral.sh/uv/getting-started/installation/
#   curl -LsSf https://astral.sh/uv/install.sh | sh
#
# Usage (from qimchi-react/ or from anywhere — the script resolves its own root):
#   bash scripts/build_macos.sh
#
# Output:
#   packaging/build/Qimchi.app         -- the macOS .app bundle (from PyInstaller)
#   packaging/build/qimchi-<tag>.dmg   -- branded installer disk image
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
cd "$REPO_ROOT"

# Match the release version key, not Ruff's target-version.
VERSION=$(grep '^[[:space:]]*version[[:space:]]*=' backend/pyproject.toml \
          | sed -E 's/.*version[[:space:]]*=[[:space:]]*"([^"]+)".*/\1/')
FRONTEND_VERSION="${QIMCHI_VERSION:-${CI_COMMIT_TAG:-}}"
if [ -z "$FRONTEND_VERSION" ]; then
    FRONTEND_VERSION=$(git tag --points-at HEAD --list 'v*' | head -1)
fi
FRONTEND_VERSION="${FRONTEND_VERSION:-$VERSION}"
echo "Building Qimchi v$VERSION for macOS (footer version: $FRONTEND_VERSION)..."

# ── 1. Frontend ───────────────────────────────────────────────────────────────
echo "Building React frontend..."
cd frontend
npm install
QIMCHI_VERSION="$FRONTEND_VERSION" npm run build
cd ..

# ── 2. Staging area ───────────────────────────────────────────────────────────
echo "Staging build files..."
mkdir -p packaging/build

# Copy canonical launcher (source of truth is packaging/qimchi_launcher.py).
cp packaging/qimchi_launcher.py packaging/build/qimchi_launcher.py

# Copy the .ico for Windows-style icon path used by the spec.
cp frontend/public/qimchi-logo.ico packaging/build/ 2>/dev/null || true

# Build the required app/volume icon from a 1024px render of the vector mark.
# A failed conversion must stop packaging instead of shipping a generic icon.
ICON_SRC="packaging/assets/qimchi-macos-icon.png"
ICNS_OUT="packaging/build/qimchi-logo.icns"
if [ ! -f "$ICON_SRC" ]; then
    echo "Error: required macOS icon source is missing: $ICON_SRC" >&2
    exit 1
fi
command -v sips >/dev/null
command -v iconutil >/dev/null
ICONSET_PARENT="$(mktemp -d)"
ICONSET="$ICONSET_PARENT/qimchi.iconset"
trap 'rm -rf "$ICONSET_PARENT"' EXIT
mkdir -p "$ICONSET"
rm -f "$ICNS_OUT"
# iconutil requires these exact filenames and sizes.
for entry in '16 16x16' '32 16x16@2x' '32 32x32' '64 32x32@2x' \
             '128 128x128' '256 128x128@2x' '256 256x256' \
             '512 256x256@2x' '512 512x512' '1024 512x512@2x'; do
    read -r size name <<< "$entry"
    sips -z "$size" "$size" "$ICON_SRC" --out "$ICONSET/icon_$name.png" >/dev/null
done
iconutil -c icns "$ICONSET" -o "$ICNS_OUT"
test -s "$ICNS_OUT"
rm -rf "$ICONSET_PARENT"
trap - EXIT
echo "  Generated $ICNS_OUT"

BACKEND_STAGE="$REPO_ROOT/packaging/build/backend_src"
rm -rf "$BACKEND_STAGE"
mkdir -p "$BACKEND_STAGE"
cp backend/main.py "$BACKEND_STAGE/"
cp -r backend/api  "$BACKEND_STAGE/"
[ -f backend/.env ] && cp backend/.env "$BACKEND_STAGE/" || true
find "$BACKEND_STAGE" -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
# Stamp the full tag so preview builds can detect the matching stable release.
cat > "$BACKEND_STAGE/api/_build_version.py" <<PYEOF
# Generated by the build script -- do not edit.
BUILD_VERSION = "$FRONTEND_VERSION"
PYEOF

# ── 3. fd binary ──────────────────────────────────────────────────────────────
# Download the ignored, bundled fd binary when missing.
echo "Ensuring vendor/fd-macos/fd is present..."
mkdir -p vendor/fd-macos
FD_DEST="vendor/fd-macos/fd"

# A truncated/failed download leaves a small fd that passes -f and then breaks
# the Explorer at runtime, so check it is plausibly a real binary.
if [ -f "$FD_DEST" ] && [ "$(wc -c < "$FD_DEST")" -lt 200000 ]; then
    echo "  fd present but looks truncated — re-downloading."
    rm -f "$FD_DEST"
fi
if [ ! -f "$FD_DEST" ]; then
    echo "  fd not found — downloading from GitHub releases..."

    ARCH=$(uname -m)
    FD_ARCH="aarch64-apple-darwin"
    [ "$ARCH" = "x86_64" ] && FD_ARCH="x86_64-apple-darwin"

    FD_JSON=$(curl -fsSL "https://api.github.com/repos/sharkdp/fd/releases/latest")
    ASSET_URL=$(echo "$FD_JSON" | python3 -c "
import sys, json
fd_arch = sys.argv[1]
data = json.load(sys.stdin)
assets = [a for a in data['assets']
          if fd_arch in a['name'] and a['name'].endswith('.tar.gz')]
if not assets:
    raise SystemExit('No fd asset found for arch: ' + fd_arch)
print(assets[0]['browser_download_url'])
" "$FD_ARCH")

    TMP=$(mktemp -d)
    curl -fsSL "$ASSET_URL" | tar -xz -C "$TMP"
    # Exclude man pages (*.1) — only pick the bare executable named "fd".
    FD_BIN=$(find "$TMP" -name "fd" -not -name "*.1" -type f | head -1)
    cp "$FD_BIN" "$FD_DEST"
    chmod +x "$FD_DEST"
    rm -rf "$TMP"
    echo "  Downloaded fd ($ARCH) to $FD_DEST"
else
    echo "  fd already at $FD_DEST"
fi

# ── 4. Python environment ─────────────────────────────────────────────────────
# Build from backend/.venv with all dataset dependencies.
echo "Setting up Python environment (backend/.venv)..."
PYTHON_EXE="backend/.venv/bin/python"
# Presence is not enough: uv garbage-collects managed base interpreters on
# upgrade, leaving a python that exists but cannot run. Verify by running it.
if [ -f "$PYTHON_EXE" ] && ! "$PYTHON_EXE" -c "import sys" >/dev/null 2>&1; then
    echo "  backend/.venv interpreter does not run (stale base Python) — recreating."
    rm -rf backend/.venv
fi
if [ ! -f "$PYTHON_EXE" ]; then
    uv venv --python 3.13 backend/.venv
fi
"$PYTHON_EXE" -c "import sys" >/dev/null

echo "Installing dependencies (backend + datasets/test extras + build tools)..."
# Include test dependencies so async tests run during packaging checks.
uv pip install --python "$PYTHON_EXE" -e "./backend[datasets,test]"
uv pip install --python "$PYTHON_EXE" pyinstaller pywebview uvicorn
# dmgbuild writes the Finder layout without AppleScript or a GUI session.
uv pip install --python "$PYTHON_EXE" "dmgbuild==1.6.7"
# copy_metadata("qimchi-api") in the spec needs the editable install's metadata.
"$PYTHON_EXE" -c "import importlib.metadata as m; m.distribution('qimchi-api')"

# ── 5. PyInstaller (.app bundle) ──────────────────────────────────────────────
echo "Building .app bundle with PyInstaller..."
APP_BUNDLE="packaging/build/Qimchi.app"
# Clear before building so the check below proves THIS run produced the bundle.
rm -rf "$APP_BUNDLE"

"$PYTHON_EXE" -m PyInstaller \
    --clean --noconfirm \
    --distpath packaging/build \
    --workpath packaging/build/pyinstaller_work \
    packaging/qimchi.spec

if [ ! -d "$APP_BUNDLE" ]; then
    echo "Error: PyInstaller reported success but $APP_BUNDLE was not produced" >&2
    exit 1
fi
echo "Built $APP_BUNDLE"

# ── 6. DMG: app icon beside the /Applications symlink ─────────────────────────
echo "Creating DMG..."
DMG_OUT="packaging/build/qimchi-${FRONTEND_VERSION}.dmg"
rm -f packaging/build/qimchi-*.dmg

# Static, Retina-ready artwork is committed; no browser or Finder is needed
# during packaging. Regenerate it with node scripts/render_dmg_artwork.mjs.
"$PYTHON_EXE" -m dmgbuild \
    -s packaging/dmg-settings.py \
    -D "app=$REPO_ROOT/$APP_BUNDLE" \
    -D "assets=$REPO_ROOT/packaging/assets" \
    "Qimchi" "$DMG_OUT"

# Both manual installation and updates use Qimchi.app at the DMG root.
DMG_CHECK="$(mktemp -d /tmp/qimchi-dmg-check.XXXXXX)"
hdiutil attach -nobrowse -noautoopen -quiet -mountpoint "$DMG_CHECK" "$DMG_OUT"
cleanup_dmg_check() {
    hdiutil detach -quiet "$DMG_CHECK"
    rmdir "$DMG_CHECK"
}
trap cleanup_dmg_check EXIT
"$PYTHON_EXE" - "$DMG_CHECK" <<'PYEOF'
import os
import plistlib
import subprocess
import sys
from pathlib import Path

from ds_store import DSStore

mount = Path(sys.argv[1])
volume = plistlib.loads(subprocess.check_output(["diskutil", "info", "-plist", str(mount)]))
assert volume["VolumeName"] == "Qimchi", volume
app = mount / "Qimchi.app"
with (app / "Contents/Info.plist").open("rb") as f:
    info = plistlib.load(f)
assert info["CFBundleName"] == "Qimchi", info
assert info["CFBundleDisplayName"] == "Qimchi", info
app_icon = app / "Contents/Resources" / info["CFBundleIconFile"]
if not app_icon.suffix:
    app_icon = app_icon.with_suffix(".icns")
assert app_icon.read_bytes().startswith(b"icns"), "App icon is missing or invalid"
volume_icon = mount / ".VolumeIcon.icns"
assert volume_icon.read_bytes() == Path("packaging/build/qimchi-logo.icns").read_bytes()
finder_info = bytes.fromhex(
    "".join(
        subprocess.check_output(
            ["xattr", "-px", "com.apple.FinderInfo", str(mount)], text=True
        ).split()
    )
)
assert int.from_bytes(finder_info[8:10], "big") & 0x0400, "Volume custom-icon flag is missing"
assert os.readlink(mount / "Applications") == "/Applications"
assert list(mount.glob(".background.*")), "DMG background is missing"
with DSStore.open(str(mount / ".DS_Store"), "r") as store:
    assert store["Qimchi.app"]["Iloc"] == (200, 260)
    assert store["Applications"]["Iloc"] == (600, 260)
    view = store["."]["icvp"]
    assert view["backgroundType"] == 2, "Finder is not using the artwork"
    assert view["iconSize"] == 128
print("Verified Qimchi volume name/icon, app icon, Applications link, artwork and Finder layout")
PYEOF
cleanup_dmg_check
trap - EXIT

DMG_MB=$(du -m "$DMG_OUT" | cut -f1)
echo "Built $REPO_ROOT/$DMG_OUT (${DMG_MB} MB)"
